export default {
  attachFiles: "Joindre des fichiers",
  bold: "Gras",
  bullets: "Puces",
  byte: "Byte",
  bytes: "Bytes",
  captionPlaceholder: "Ajouter une description…",
  code: "Code",
  heading1: "Titre",
  indent: "Augmenter l'indentation",
  italic: "Italique",
  link: "Lien",
  numbers: "Nombres",
  outdent: "Réduire l'indentation",
  quote: "Citation",
  redo: "Refaire",
  remove: "Supprimer",
  strike: "Barré",
  undo: "Annuler",
  unlink: "Supprimer le lien",
  url: "URL",
  urlPlaceholder: "Entrez une URL…",
  GB: "GB",
  KB: "KB",
  MB: "MB",
  PB: "PB",
  TB: "TB",
}
